### ISSUE TITLE
공동번역 - 번역할 Part 찜하기! 

### ISSUE THREAD

**Issue by nassol** [EngForDev/AngularJSStudy#4]
Angular JS를 스터디하는 두 가지 방법 중 하나로, [이 글](https://thinkster.io/angulartutorial/a-better-way-to-learn-angularjs/)을 공동번역 합니다. 어떤 글이 링크가 되어 있다면, 그 글도 저자에게 동의를 구해서 번역하려고 해요. 글을 맡으신 분이 저자에게 동의 구하는 부분도 연락해주시면 감사드리겠습니다 :)

Angular JS 스터디 방법 두 가지 모두를 보시려면 [이글](https://github.com/EngForDev/AngularJSStudy)을 보시구요.

아무도 맡지 않은 파트를 골라 주시고, 번역하시려는 파트를 골라서 댓글로 적어주세요~ 
단, 각 파트의 내용과, 그 파트에 링크된 글도 번역하는 것이니 안에 링크된 내용을 잘 보시고 판단해 주세요~
# 공동번역 파트 분담 현황
- Part 1 @nassol
- Part 2 @ujuc 
- Part 3 @ujuc 
- Part 4 @juyoungbang
- Part 5 @irondog 
- Part 6 @irondog 
- Part 7 @fermat39 
- Part 8 @fermat39 
- Part 9
- Part 10
- Part 11
- Part 12 @irondog 
- Part 13

**Comment by irondog** [comment]
저는 경험이 있어서 part10 이후의 내용을 선택해서 번역 할게요. part10이후의 모두를 번역하겠다는게 아니라 그 중에 몇개를 한다는 뜻입니다. 어서들 찜 하세요!!!

**Comment by nassol** [comment]
@irondog  좋습니다~ 파트 하나 콕 찝어 주세요~

**Comment by irondog** [comment]
전 part 6, 12 먼저 쨈해 봅니다.

**Comment by ujuc** [comment]
@nassol 2,3 신청요

**Comment by nassol** [comment]
@juyoungbang  아.. 생각해보니 번역해도 되는지 허락을 받았는지 모르네요 :) 혹시 답이 왔나요?

**Comment by bangjuyoung** [comment]
@nassol 지금 답변 기다리고 있어요ㅠㅠ 원래 늦게 오는 건지 아니면 제가 영어가 부족했던 걸까요ㅠㅠ 오늘 저녁에 다시 보내 볼까봐요ㅠ

**Comment by bangjuyoung** [comment]
전 PART 4 directives 할께요~!

**Comment by nassol** [comment]
@juyoungbang  그렇군용! 트위터같은 것으로도 날려보세요~

**Comment by fermat39** [comment]
일단 전 7, 8 지릅니다!!!

**Comment by nassol** [comment]
@fermat39  좋습니다~~ 고고고~~

**Comment by nassol** [comment]
저는 part1 할게요~ 연결된 이 문서들을 제대로 잘 번역할 수 있을지 모르지만, 일단 하는데까정!

**Comment by irondog** [comment]
신청자 더 없으시면 Part 5도 제가 하겠습니다. 3,4,5가 사실 내용이 어마어마하게 많은데 문서 자체는 양이 많지 않은듯...

**Comment by nassol** [comment]
저는 뒤늦게 part1 하고 있네요 ㅎㅎ  일단 draft만 했지만.. ㅎㅎ
